language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
install:
  # this fixes SemLock issues on travis
  - "pip install cython"
  - "make test_setup"
  - "python setup.py develop"
env:
  matrix: 
    - COMMAND="make test"
    - COMMAND="make cybuild test""
script: "$COMMAND"
